-- ============================================================
-- RUAI TV — Database Schema & Data Seeder
-- Database Name: ruai_tv
-- Host: localhost (XAMPP MySQL)
-- ============================================================

CREATE DATABASE IF NOT EXISTS `ruai_tv` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `ruai_tv`;

-- --------------------------------------------------------
-- Table structure for table `programs`
-- --------------------------------------------------------

DROP TABLE IF EXISTS `programs`;
CREATE TABLE `programs` (
  `id` VARCHAR(64) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `category` ENUM('berita', 'non-news', 'kerja-sama') NOT NULL DEFAULT 'berita',
  `category_label` VARCHAR(100) DEFAULT NULL,
  `status` ENUM('aktif', 'arsip') NOT NULL DEFAULT 'aktif',
  `format` VARCHAR(100) DEFAULT '—',
  `duration` VARCHAR(50) DEFAULT '—',
  `description` TEXT DEFAULT NULL,
  `thumbnail_url` VARCHAR(255) DEFAULT NULL,
  `promo_video_url` VARCHAR(255) DEFAULT NULL,
  `youtube_live_url` VARCHAR(255) DEFAULT NULL,
  `schedule_json` LONGTEXT DEFAULT NULL,
  `featured` TINYINT(1) DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_category` (`category`),
  KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------
-- Dumping data for table `programs`
-- --------------------------------------------------------

INSERT INTO `programs` (`id`, `title`, `slug`, `category`, `category_label`, `status`, `format`, `duration`, `description`, `thumbnail_url`, `promo_video_url`, `youtube_live_url`, `schedule_json`, `featured`) VALUES
('warta-ruai', 'Warta Ruai', 'warta-ruai', 'berita', 'Program Berita', 'aktif', 'Berita', '60 Menit', 'Paket buletin berita hasil liputan harian pada peristiwa dan isu aktual yang terjadi di Pontianak dan sekitarnya, serta Kalimantan Barat pada umumnya. Tayang tiga kali sehari — pagi, siang, dan malam — untuk memastikan pemirsa selalu mendapatkan informasi terkini.', 'assets/images/programs/Warta-Ruai.png', 'https://www.youtube.com/embed/live_stream?channel=UCruaitv', 'https://www.youtube.com/@ruaitv/live', '{"pagi": {"active": true, "label": "PAGI", "time": "07.00 – 08.00 WIB", "days": "Senin - Sabtu"}, "siang": {"active": true, "label": "SIANG", "time": "13.00 – 14.00 WIB", "days": "Senin - Sabtu"}, "malam": {"active": true, "label": "MALAM", "time": "19.00 – 20.00 WIB", "days": "Senin - Sabtu"}}', 1),
('ruai-sepekan', 'Ruai Sepekan', 'ruai-sepekan', 'berita', 'Program Berita', 'aktif', 'Buletin Berita', '30 Menit', 'Rangkuman berita terhangat atau berita-berita utama selama sepekan dari Warta Ruai. Disajikan secara interaktif di mana publik memiliki ruang untuk mengomentari, mempertanyakan, dan memberikan opini terhadap materi berita atau permasalahan yang menjadi isi berita.', 'assets/images/programs/Ruai-Sepekan.png', NULL, 'https://www.youtube.com/@ruaitv/live', '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": true, "label": "MALAM", "time": "19.30 – 20.00 WIB", "days": "Minggu"}}', 0),
('warta-warganet', 'Warta Warganet', 'warta-warganet', 'berita', 'Program Berita', 'aktif', 'Buletin Berita', '30 Menit', 'Acara yang digagas untuk memberi ruang dan menghargai WargaNet di Media Arustama. Memberikan apresiasi atas karya spontanitas maupun terencana terhadap segala kekayaan adat budaya, lingkungan, alam dan bahkan kesenjangan sosial yang tertangkap mata kamera Warganet.', 'assets/images/programs/WargaNet.png', NULL, 'https://www.youtube.com/@ruaitv/live', '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": true, "label": "SIANG", "time": "18.30 – 19.00 WIB", "days": "Selasa & Jumat"}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('rumah-kita', 'Rumah Kita', 'rumah-kita', 'berita', 'Program Berita', 'aktif', 'Talkshow / Podcast', '60 Menit', 'Program bincang-bincang/podcast inspiratif yang mengangkat kisah hidup, dedikasi, perjuangan, serta kiprah para tokoh publik, pemuka agama, pelaku seni, maupun individu inspiratif di Kalimantan Barat dalam melayani dan memberikan dampak positif bagi komunitas serta masyarakat luas.', 'assets/images/programs/Rumah-Kita.png', NULL, 'https://www.youtube.com/@ruaitv/live', '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": true, "label": "MALAM", "time": "20.05 – 21.05 WIB", "days": "Senin"}}', 0),
('forum-ruai', 'Forum Ruai', 'forum-ruai', 'berita', 'Program Berita', 'aktif', 'Talkshow', '60 Menit', 'Forum Ruai Adalah ruang diskusi kritis yang sehat untuk memaparkan suatu masalah yang sedang terjadi maupun yang mungkin akan terjadi, membedah dari berbagai sudut pandang intelektualitas dengan kritis dan professional dan selalu memberi rekomendasi diakhir acara.', 'assets/images/programs/Forum-Ruai.png', NULL, 'https://www.youtube.com/@ruaitv/live', '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": true, "label": "MALAM", "time": "20.05 – 21.05 WIB", "days": "Kamis"}}', 0),
('special-dialog', 'Special Dialog', 'special-dialog', 'berita', 'Program Berita', 'aktif', 'Talkshow', '60 Menit', 'Program dialog mendalam yang membahas isu-isu strategis politik, ekonomi, sosial, dan budaya bersama narasumber terpilih dari kalangan pejabat, pakar, dan tokoh masyarakat Kalimantan Barat.', 'assets/images/programs/Spesial-Dialog.png', NULL, 'https://www.youtube.com/@ruaitv/live', '{"pagi": {"active": true, "label": "PAGI", "time": "Tentatif / Kondisioanl", "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('kilas-ruai', 'Kilas Ruai', 'kilas-ruai', 'berita', 'Program Berita', 'arsip', 'Breaking News', '—', 'Kilas ruai adalah ruang aktual penyajian berita dari berbagai jenis peristiwa yang terjadi disetiap redaksi mendapat informasi yang langsung direspon dengan cepat, cekat dan profesional tanpa mengurangi nilai kebenaran peristiwa. Selalu mengacu kepada 5W+1H', 'assets/images/programs/Kilas-Ruai.png', NULL, 'https://www.youtube.com/@ruaitv/live', '{"pagi": {"active": true, "label": "PAGI", "time": "10.00 WIB", "days": "Senin - Sabtu"}, "siang": {"active": true, "label": "SORE", "time": "15.00 WIB", "days": "Senin - Sabtu"}, "malam": {"active": true, "label": "SORE", "time": "17.00 WIB", "days": "Senin - Sabtu"}}', 0),
('gong-ruai', 'Gong Ruai (On Target)', 'gong-ruai', 'berita', 'Program Berita', 'arsip', 'News Feature', '30 Menit', 'Acara Gong Ruai adalah ruai dokumenter reporting indept terhadap suatu kasus atau masalah yang sedang menjadi perhatian publik atau masyarakat tertentu seperti isu pengukuhan dan atau pengakuan akan hak masyarakat adat. Laporannya lebih dalam, tajam, kritis dan solutif. Menyajikan data primer, data sekunder dan sudut pandang dari sejumlah pakar dan pihak-pihak yang terlibat dalam topik dokumenter.', 'assets/images/programs/Warta-Ruai.png', NULL, NULL, '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('warta-ruai-3-bahasa', 'Warta Ruai 3 Bahasa', 'warta-ruai-3-bahasa', 'berita', 'Program Berita', 'arsip', 'Program Berita / Talkshow', '—', 'Program berita unggulan Ruai TV yang disajikan dalam lima bahasa daerah Kalimantan Barat, menjangkau berbagai komunitas etnis di seluruh pelosok Kalbar.', 'assets/images/programs/Warta-Ruai.png', NULL, NULL, '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('warta-credit-union', 'Warta Credit Union', 'warta-credit-union', 'berita', 'Program Berita', 'arsip', '—', '—', 'Jendela berita ekonomi kerakyatan berbasis koperasi simpan pinjam (Credit Union) di Kalimantan Barat, salah satu gerakan CU terbesar di Indonesia.', 'assets/images/programs/Warta-Ruai.png', NULL, NULL, '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('slada-video-klip', 'Slada Video Klip', 'slada-video-klip', 'non-news', 'Non-News', 'aktif', 'Hiburan', '—', 'Program hiburan yang menayangkan video klip musik pilihan, menemani pemirsa Ruai TV dengan sajian musik terbaik dari berbagai genre.', 'assets/images/programs/Slada.png', NULL, 'https://www.youtube.com/@ruaitv/live', '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('galeri-khatulistiwa', 'Galeri Khatulistiwa', 'galeri-khatulistiwa', 'non-news', 'Non-News', 'arsip', 'Dokumenter', '—', 'Tayangan dokumenter yang menampilkan keindahan alam dan budaya Kalimantan Barat serta Nusantara dalam format visual yang memukau.', 'assets/images/programs/Borneo-Rawa-Island.png', NULL, 'https://www.youtube.com/', '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('slada-reguler', 'Slada Reguler', 'slada-reguler', 'non-news', 'Non-News', 'arsip', 'Hiburan', '—', 'Senandung Lagu Daerah (SLADA) reguler — program yang melestarikan dan memopulerkan lagu-lagu daerah Kalimantan Barat dalam format tayangan yang modern.', 'assets/images/programs/Slada.png', NULL, 'https://www.youtube.com/', '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('slada-week-end', 'Slada Week End', 'slada-week-end', 'non-news', 'Non-News', 'arsip', 'Hiburan', '—', 'Edisi akhir pekan dari program Senandung Lagu Daerah (SLADA) yang hadir dengan nuansa lebih santai dan pilihan lagu yang lebih beragam untuk menemani waktu weekend keluarga.', 'assets/images/programs/Slada.png', NULL, 'https://www.youtube.com/', '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('kapuas-karaoke', 'Kapuas (Karaoke Sampai Puas)', 'kapuas-karaoke', 'non-news', 'Non-News', 'arsip', 'Hiburan', '—', 'Program interaktif karaoke yang mengundang pemirsa untuk ikut bernyanyi bersama dan menikmati lagu-lagu favorit dalam format hiburan yang menyenangkan.', 'assets/images/programs/Slada.png', NULL, 'https://www.youtube.com/', '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('penyejuk-iman', 'Penyejuk Iman', 'penyejuk-iman', 'non-news', 'Non-News', 'arsip', 'Religi', '—', 'Program rohani yang menghadirkan ceramah, renungan, dan tayangan inspiratif untuk memperkuat keimanan dan spiritualitas pemirsa Ruai TV.', 'assets/images/programs/Warta-Ruai.png', NULL, 'https://www.youtube.com/', '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('masakan-istimewa', 'Masakan Istimewa (Maskis)', 'masakan-istimewa', 'non-news', 'Non-News', 'arsip', 'Kuliner', '—', 'Program kuliner yang mengeksplorasi kekayaan cita rasa masakan khas dan istimewa Kalimantan Barat, menghadirkan resep, teknik memasak, dan cerita di balik hidangan tradisional maupun modern.', 'assets/images/programs/Warta-Ruai.png', NULL, NULL, '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('pantun-rias', 'Pantun Rias', 'pantun-rias', 'non-news', 'Non-News', 'arsip', 'Seni Budaya', '—', 'Ruang pelestarian seni pantun dan sastra lisan Melayu Kalimantan Barat yang menampilkan pertunjukan pantun, syair, dan gurindam dari seniman lokal terpilih.', 'assets/images/programs/Warta-Ruai.png', NULL, NULL, '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('voa-jalan-jalan', 'VOA — Jalan-Jalan Amerika', 'voa-jalan-jalan', 'kerja-sama', 'Kerja Sama', 'aktif', 'Dokumenter', '30 Menit', 'Program hasil kerja sama Ruai TV dengan Voice of America (VOA) yang menghadirkan tayangan dokumenter perjalanan dan budaya Amerika untuk pemirsa Kalimantan Barat.', 'assets/images/programs/VOA-Jalan-Jalan-Amerika.png', NULL, 'https://www.youtube.com/@ruaitv/live', '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": true, "label": "SIANG", "time": "Menyesuaikan", "days": "Cek jadwal"}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('voa-warung-kita', 'VOA — Warung Kita', 'voa-warung-kita', 'kerja-sama', 'Kerja Sama', 'aktif', 'Feature', '—', 'Program kerja sama dengan VOA yang menghadirkan konten feature khas kearifan lokal dan budaya Nusantara dalam sudut pandang internasional VOA.', 'assets/images/programs/VOA-Warung-Kita.png', NULL, 'https://www.youtube.com/@ruaitv/live', '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('borneo-rawa-island', 'Borneo Rawa Island', 'borneo-rawa-island', 'kerja-sama', 'Kerja Sama', 'aktif', 'Dokumenter', '—', 'Program dokumenter hasil kerja sama yang mengeksplorasi kekayaan alam, ekosistem gambut, dan kehidupan di pulau Borneo/Kalimantan.', 'assets/images/programs/Borneo-Rawa-Island.png', NULL, 'https://www.youtube.com/@ruaitv/live', '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('cbn-solusi', 'CBN — Solusi', 'cbn-solusi', 'kerja-sama', 'Kerja Sama', 'aktif', 'Talkshow', '—', 'Program talkshow hasil kerja sama dengan CBN yang menghadirkan solusi praktis untuk berbagai permasalahan kehidupan sehari-hari.', 'assets/images/programs/CBN-Solusi.png', NULL, 'https://www.youtube.com/', '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('cbn-dialog-jc', 'CBN — Dialog JC', 'cbn-dialog-jc', 'kerja-sama', 'Kerja Sama', 'aktif', 'Talkshow', '—', 'Program dialog kerja sama dengan CBN yang membahas berbagai topik kehidupan dan iman dari sudut pandang yang mencerahkan.', 'assets/images/programs/CBN-Solusi.png', NULL, 'https://www.youtube.com/@ruaitv/live', '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('cbn-super-youth', 'CBN — Super Youth', 'cbn-super-youth', 'kerja-sama', 'Kerja Sama', 'aktif', 'Youth Program', '—', 'Program anak muda hasil kerja sama CBN dan Ruai TV yang menghadirkan konten inspiratif, edukatif, dan menghibur untuk generasi muda Kalimantan Barat.', 'assets/images/programs/CBN-Super-Youth.png', NULL, 'https://www.youtube.com/@ruaitv/live', '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('cbn-super-book', 'CBN — Super Book', 'cbn-super-book', 'kerja-sama', 'Kerja Sama', 'aktif', 'Animasi Anak', '—', 'Tayangan animasi anak-anak berbasis kisah inspiratif hasil kerja sama dengan CBN, menghadirkan nilai moral dan karakter positif untuk anak-anak.', 'assets/images/programs/CBN-Super-Youth.png', NULL, 'https://www.youtube.com/', '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('voa-dunia-kita', 'VOA — Dunia Kita', 'voa-dunia-kita', 'kerja-sama', 'Kerja Sama', 'arsip', 'Feature Berita', '—', 'Wawasan dunia internasional dari Voice of America (VOA) yang menyajikan feature-feature menarik tentang kehidupan dan perkembangan global.', 'assets/images/programs/VOA-Jalan-Jalan-Amerika.png', NULL, 'https://www.youtube.com/', '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('ananda-buana', 'Ananda Buana', 'ananda-buana', 'kerja-sama', 'Kerja Sama', 'arsip', 'Dokumenter', '—', 'Dokumenter alam liar dan eksplorasi Borneo yang mengangkat kekayaan biodiversitas dan keunikan ekosistem Kalimantan. Saat ini dalam status arsip.', 'assets/images/programs/Borneo-Rawa-Island.png', NULL, NULL, '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('antara', 'Antara', 'antara', 'kerja-sama', 'Kerja Sama', 'arsip', 'Berita', '—', 'Tayangan religi kerja sama yang menghadirkan ceramah dan pencerahan spiritual dari narasumber terpilih untuk masyarakat Kalimantan Barat.', 'assets/images/programs/Warta-Ruai.png', NULL, NULL, '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('ringkus', 'Ringkus (Ringkasan Kriminal)', 'ringkus', 'berita', 'Program Berita', 'arsip', 'Feature Berita', '—', 'Program ringkasan berita kriminal yang menyajikan laporan singkat dan aktual tentang peristiwa hukum dan kriminalitas di Kalimantan Barat.', 'assets/images/programs/Warta-Ruai.png', NULL, NULL, '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('bersama-sosok', 'Bersama Sosok', 'bersama-sosok', 'berita', 'Program Berita', 'arsip', 'Feature / Talkshow', '—', 'Program yang mengangkat profil dan kisah inspiratif tokoh-tokoh berpengaruh di Kalimantan Barat dari berbagai bidang kehidupan.', 'assets/images/programs/Warta-Ruai.png', NULL, NULL, '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('pentas-aksi', 'Pentas Aksi', 'pentas-aksi', 'non-news', 'Non-News', 'arsip', 'Hiburan', '—', 'Program hiburan yang menampilkan pertunjukan seni dan aksi panggung dari para seniman dan pelaku seni budaya Kalimantan Barat.', 'assets/images/programs/Warta-Ruai.png', NULL, NULL, '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('bincang-cu', 'Bincang CU', 'bincang-cu', 'non-news', 'Non-News', 'arsip', 'Talkshow', '—', 'Program bincang-bincang seputar dunia Credit Union (CU) dan koperasi simpan pinjam di Kalimantan Barat, menghadirkan edukasi finansial berbasis ekonomi kerakyatan.', 'assets/images/programs/Warta-Ruai.png', NULL, NULL, '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('bursa-musik-ruai', 'Bursa Musik Ruai (BMR)', 'bursa-musik-ruai', 'non-news', 'Non-News', 'arsip', 'Hiburan Musik', '—', 'Program musik Ruai TV yang menghadirkan bursa lagu-lagu pilihan dari berbagai genre, menemani pemirsa dengan sajian musik terbaik dari artis lokal dan nasional.', 'assets/images/programs/Warta-Ruai.png', NULL, NULL, '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('bumi-hijau', 'Bumi Hijau', 'bumi-hijau', 'kerja-sama', 'Kerja Sama', 'arsip', 'Dokumenter', '—', 'Berita nasional dan daerah dari kantor berita ANTARA yang disiarkan melalui Ruai TV untuk melengkapi cakupan informasi bagi pemirsa Kalimantan Barat.', 'assets/images/programs/Warta-Ruai.png', NULL, NULL, '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0),
('beranda-ruai', 'Beranda Ruai', 'beranda-ruai', 'non-news', 'Non-News', 'arsip', 'Hiburan', '—', 'Program Non-News Ruai TV yang menghadirkan konten hiburan dan informasi ringan untuk menemani pemirsa di rumah.', 'assets/images/programs/Warta-Ruai.png', NULL, NULL, '{"pagi": {"active": false, "label": "PAGI", "time": null, "days": null}, "siang": {"active": false, "label": "SIANG", "time": null, "days": null}, "malam": {"active": false, "label": "MALAM", "time": null, "days": null}}', 0);
